services:
  spang-prod:
    image: spang:cognito_prod
    container_name: spang_cognito_prod
    build:
      context: ./
    volumes:
      - type: bind
        source: /kaiac/spang/tmp
        target: /app/tmp/
    ports:
        - '4200:4200'