services:
  cogspa-keycloak-prod:
    image: keycloak:cogspa_prod
    container_name: cogspa_keycloak_prod
    build:
      context: ./
    volumes:
      - type: bind
        source: /kaiac/cogspa/tmp
        target: /app/tmp/
    ports:
        - '8083:8083'